# Generated by Django 2.2.4 on 2019-09-03 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=100)),
                ('singer', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('songs_no', models.IntegerField()),
                ('album_logo', models.FileField(upload_to='media')),
            ],
        ),
    ]
